### ISSUE TITLE
order_report() api is failing for live account

### ISSUE THREAD

**Issue by ketanwangade** [Kotak-Neo/kotak-neo-api#103]
Hi Kotak Team,

I am getting a below error after calling the order_report() api from live account. Can you please guide me on how to resolve this issue.
Also where i can find your stCode documentation, I am not able to understand what is 5203 status code means.

```
Error is : {'stat': 'Not_Ok', 'errMsg': 'No Data', 'stCode': 5203, 'tid': 'server4_3946598'}
```

**Comment by rosevinod** [comment]
@ketanwangade 
that means you did not place any order.
place an order, you will get the result.

**Comment by shitizbansal247** [comment]
i am facing a similar problem. if i run a strategy at lets say 8:45. it trades at 9:17 but it still shows 'No Data' in order report. When i re-run the code, it works fine. I think its something related to websockets. if someone can help me i will be truly grateful
