### ISSUE TITLE
Python 3.12 Fails Installation

### ISSUE THREAD

**Issue by ihimanshurawat** [Kotak-Neo/kotak-neo-api#105]
Hello,
With Python 3.12 the installation is failing. 

Error - AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

I downgraded to Python 3.11.7 and installed it successfully.

We can add a callout to avoid confusion.

**Comment by crypt0inf0** [comment]
Change the numpy version from `numpy==1.24.2` to `numpy` on `setup.py` file will complete the package install.
