### ISSUE TITLE
how to place a basket order & how to calculate required margin

### ISSUE THREAD

**Issue by crypt0inf0** [Kotak-Neo/kotak-neo-api#106]
Hi, Does anyone know how to place a basket order and calculate required margin using the API.

Doc from https://github.com/Kotak-Neo/kotak-neo-api/blob/main/docs/Margin_Required.md#margin_required shows only one script rather than multiple scripts.

Can anyone please explain with a example.

Thanks

**Comment by rosevinod** [comment]
@crypt0inf0  you can not place basket order using Kotak API.

**Comment by crypt0inf0** [comment]
@rosevinod Thanks, @Kotak-Neo Is there any future plan to add basket order to the API?

**Comment by Kotak-Neo** [comment]
We have taken your feedback and will evaluate it internally. :)
