### ISSUE TITLE
place_order() not accepting MCX or mcx_fo as a segment.

### ISSUE THREAD

**Issue by ChirayuBhatia** [Kotak-Neo/kotak-neo-api#107]
Getting: {'Error': neo_api_client.exceptions.ApiValueError('Invalid exchange segment. Allowed values are NSE or nse_cm, BSE or bse_cm, NFO or nse_fo, BFO or bse_fo, CDS or cde_fo, BCD or bcs_fo.')}

The Readme.md shows that MCX is allowed but the SDK is not allowing.

**Comment by shekar3110a** [comment]
ARE THERE ANY UPDATE IN THIS FRONT .. ALSO THE WEBSOCKET DOES NOT GET THE UPDATE FOR MCX OPTIONS REGULARLY AFTER 15.30 .. 

SHEKAR

**Comment by Prateekm11** [comment]
Guys do you really care about your customers at kotak security. there is no response and no one pick this issue.
