### ISSUE TITLE
client.subscribe custom on_message callback 

### ISSUE THREAD

**Issue by crypt0inf0** [Kotak-Neo/kotak-neo-api#110]
How to use custom `on_message` on [neo_api_client.subscribe](https://github.com/Kotak-Neo/kotak-neo-api/blob/main/docs/webSocket.md#subscribe)

```
live_data = {}

def on_feed(message):
    global live_data
    try:
        print(f"message : {message}")
        for i in message:
            live_data[i['ts']] = i['ltp']
    except Exception as e:
        print(f"Error {e}")

inst_tokens = [{"instrument_token": "65373", "exchange_segment": "nse_fo"}]

def stream():
    c.subscribe(instrument_tokens=inst_tokens, on_message=on_feed)

Thread(target=stream).start()
```

@Kotak-Neo Can you add this functionality?

**Comment by crypt0inf0** [comment]
i use https://github.com/Kotak-Neo/kotak-neo-api/pull/63

**Comment by Kotak-Neo** [comment]
We are soon releasing a new version which will contain the same. Will keep you guys posted :)

**Comment by Hari3115** [comment]
@Kotak-Neo When is the new version coming up? the callback function is not working for anyone trying it lately
