### ISSUE TITLE
What are should be the mobile number and password/mpin to be used for uat environtment?

### ISSUE THREAD

**Issue by amateur-veteran** [Kotak-Neo/kotak-neo-api#119]
When i try with my actual phone number and password/mpin i get error as in screenshot. The code works fine for prod. Also while passing uat, i updated the consumer secret and consumer key of sandbox environment
<img width="1384" alt="image" src="https://github.com/Kotak-Neo/kotak-neo-api/assets/61919375/57e3f08e-6614-491c-ac68-6f5c89653a7d">

**Comment by amateur-veteran** [comment]
1. What are the credentials to be used for sandbox env?
2. if any code change for uat login, please lemme know

**Comment by Kotak-Neo** [comment]
For UAT access kindly drop a mail to neo.api@kotak.com
