### ISSUE TITLE
place order endpoint not working

### ISSUE THREAD

**Issue by amateur-veteran** [Kotak-Neo/kotak-neo-api#126]
<img width="615" alt="image" src="https://github.com/Kotak-Neo/kotak-neo-api/assets/61919375/6de4c587-585a-4fd9-95a9-1f2107c3e284">

check the screenshot attached. This has been reported by multiple users in the developer portal as well.

**Comment by amateur-veteran** [comment]
Even the SDK is giving the same. How the chains are getting changed when the bike is on road :/
<img width="1389" alt="image" src="https://github.com/Kotak-Neo/kotak-neo-api/assets/61919375/22752a9f-1f53-4bdc-b245-5c5dee26adb6">

**Comment by dsp1589** [comment]
why would someone close this.. still facing this error :( SDKs released with testing or incomplete documentation!!
