### ISSUE TITLE
repeatedly facing Error while initialising login 

### ISSUE THREAD

**Issue by dikshantpatel27** [Kotak-Neo/kotak-neo-api#137]
while initiating login an error related to concatenation of strings is repeatedly occurring despite all login credentials being correct.
**TypeError: can only concatenate str (not "NoneType") to str**
Please help to rectify this.

![Screenshot 2024-02-06 113717](https://github.com/Kotak-Neo/kotak-neo-api/assets/157000452/e95110c9-2f7b-433f-ac6d-c4587ea4ac98)

**Comment by knkrth** [comment]
@dikshantpatel27 If you are using env variable for `consumer_key` and `consumer_secret` as `consumerkey` & `secretkey` you need to remove the double quotes like,
```
consumerkey = "x123apikey321"
secretkey = "x123apisecret321"

client = NeoAPI(consumer_key=consumerkey, consumer_secret=secretkey, environment='prod')
```
you need to removed the quotes from mobile, password and mpin aswell.

**Comment by dikshantpatel27** [comment]
Thanks a lot @knkrth
