### ISSUE TITLE
Client OrderID already exists

### ISSUE THREAD

**Issue by APItrad** [Kotak-Neo/kotak-neo-api#150]
{'stat': 'Not_Ok',
 'errMsg': 'Put Order Response : Client OrderID already exists',
 'tid': 'server5_526372',
 'stCode': 5204}
even after i cancel the order it still prompts this response. not able to place multiple orders. this code works only once a day.
orderRes= client.place_order(exchange_segment='nse_fo', product='MIS', price='1', order_type='L', quantity='1800', validity='DAY', trading_symbol='BANKNIFTY2432046400CE',
                    transaction_type='B', amo="NO", disclosed_quantity="0", market_protection="0", pf="N",
                    trigger_price="0", tag='Umang')
orderRes

**Comment by APItrad** [comment]
@Kotak-Neo

**Comment by abimk9** [comment]
Possibly because you are using same tag for the orders placed in same day

**Comment by APItrad** [comment]
Its working now.
