### ISSUE TITLE
not able to get the SEXSEX and BANKEX data from nse_fo segment dataset

### ISSUE THREAD

**Issue by Sunil2k1S** [Kotak-Neo/kotak-neo-api#159]
Hi,

Please add the SEXSEX and BANKEX data in below dataset which we are generating on daily basis .
https://lapi.kotaksecurities.com/wso2-scripmaster/v1/prod/2024-04-19/transformed/nse_fo.csv    

<img width="131" alt="image" src="https://github.com/Kotak-Neo/kotak-neo-api/assets/40523236/54f8c948-19e7-4e2c-bb78-62b374efaaf7">

As we can only see 'NIFTY','BANKNIFTY','FINNIFTY','MIDCPNIFTY'  THESE 4 INDEX but not  SEXSEX and BANKEX , 
can you please show how to get them as well ?

Thanks

**Comment by crypt0inf0** [comment]
Script master has separate `.csv` url for different segments,

```
import subprocess

# Get Scrip Master CSV file
scripMaster  = c.scrip_master()
bse_cm = scripMaster['filesPaths'][0]
cde_fo = scripMaster['filesPaths'][1]
mcx_fo = scripMaster['filesPaths'][2]
nse_cm = scripMaster['filesPaths'][3]
nse_fo = scripMaster['filesPaths'][4]
bse_fo = scripMaster['filesPaths'][5]

# Specify the file name you want to save as
file_name = 'bse_cm.csv'

# Using curl to download the file
subprocess.run(['curl', '-o', file_name, bse_cm])
```

**Comment by Sunil2k1S** [comment]
tHANKS
