### ISSUE TITLE
getting error: HTTPSConnectionPool(host='napi.kotaksecurities.com', port=443): Max retries exceeded with url: /oauth2/token 

### ISSUE THREAD

**Issue by Sunil2k1S** [Kotak-Neo/kotak-neo-api#182]
getting error: HTTPSConnectionPool(host='napi.kotaksecurities.com', port=443): Max retries exceeded with url: /oauth2/token 

ERROR msg (0)
Reason: ConnectTimeout
HTTPSConnectionPool(host='napi.kotaksecurities.com', port=443): Max retries exceeded with url: /oauth2/token (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001B9383AFF90>, 'Connection to napi.kotaksecurities.com timed out. (connect timeout=None)'))

**Comment by Sunil2k1S** [comment]
![Uploading image.png…]()

**Comment by nprejit** [comment]
give your code or screenshot

**Comment by Sunil2k1S** [comment]
resolved .
