### ISSUE TITLE
Access failure for API: /Orders/2.0, version: 2.0 status: (900901) - Invalid Credentials. Make sure you have provided the correct security credentials

### ISSUE THREAD

**Issue by Anjan-99** [Kotak-Neo/kotak-neo-api#183]
data: {
      code: '900901',
      message: 'Invalid Credentials',
      description: 'Access failure for API: /Orders/2.0, version: 2.0 status: (900901) - Invalid Credentials. Make sure you have provided the correct security credentials'
    }
    
    getting this error while square off order

**Comment by nprejit** [comment]
give your request code
