### ISSUE TITLE
from neo_api_client import NeoApi Traceback (most recent call last):   File "<pyshell#0>", line 1, in <module>     from neo_api_client import NeoApi ImportError: cannot import name 'NeoApi' from 'neo_api_client' (C:\Users\BAPS\AppData\Local\Programs\Python\Python311\Lib\site-packages\neo_api_client\__init__.py)

### ISSUE THREAD

**Issue by Jignesh108108** [Kotak-Neo/kotak-neo-api#198]
While installing it says requirement satisfied but still giving below error
from neo_api_client import NeoApi
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    from neo_api_client import NeoApi
ImportError: cannot import name 'NeoApi' from 'neo_api_client' (C:\Users\BAPS\AppData\Local\Programs\Python\Python311\Lib\site-packages\neo_api_client\__init__.py)

**Comment by comeback2000** [comment]
I am using docker facing same issue 

PS F:\Kotak\kotak-neo-api> docker logs kotak-api
/usr/local/bin/python3: No module named neo_api_client.__main__; 'neo_api_client' is a package and cannot be directly executed
