### ISSUE TITLE
issue with the live feed

### ISSUE THREAD

**Issue by echnidia-atig** [Kotak-Neo/kotak-neo-api#205]
Warning!
on_message callback is not Set
on_error callback is not Set
on_close callback is not Set
on_open callback is not Set
It is recommended to set callbacks to handle your own logic on events.

I get the above warning after trying to run the code below.

client.subscribe(instrument_tokens = instrument_tokens, isIndex=False, isDepth=False)

Why? and how to resolve it.

**Comment by dkripalani** [comment]
def on_message(message):
    print(message)
    
def on_error(error_message):
    print(error_message)

add these two in your code. Hope fully it should work

**Comment by echnidia-atig** [comment]
> def on_message(message): print(message)
> 
> def on_error(error_message): print(error_message)
> 
> add these two in your code. Hope fully it should work

they are already added but still it is showing this error
and when i add this piece of code in another cell and then run the live feed code it just exits to the the next cell without any output

**Comment by nprejit** [comment]
@echnidia-atig 
giving you the code try this

live_data = None

def on_connect(ws, message):
    print('[OnOpen]: ', message)
    
def on_ticks(ws, message):
    global live_data
    print('[Res]: ', message)
    live_data = message

def on_close(ws, code, message):
    print('[OnClose]: ',code, message)

def on_error(ws, code, message):
    print('[OnError]: ', code, message)

client.on_open = on_connect
client.on_message = on_ticks
client.on_error = on_error
client.on_close = on_close

#for Index NIFTY, BANKNIFTY
inst_tokens = [{"instrument_token": "26000", "exchange_segment": "nse_cm"},
               {"instrument_token": "26009", "exchange_segment": "nse_cm"}]
client.subscribe(instrument_tokens=inst_tokens, isIndex=True, isDepth=False)
print(live_data)

#for Equity Stock
inst_tokens = [{"instrument_token": "2885", "exchange_segment": "nse_cm"},
               {"instrument_token": "1594", "exchange_segment": "nse_cm"}]
client.subscribe(instrument_tokens=inst_tokens, isIndex=False, isDepth=False)
print(live_data)

**Comment by echnidia-atig** [comment]
@nprejit 
Thank you it worked 
this code didn't give any error 
but i want it to continuously give me data in real time this is giving me just one output

is there any way or post i can refer to regarding that??

**Comment by nprejit** [comment]
it will give continuous output in real time whenever new ticks happen. you checked in off market that is why it shows only once. When the market is closed, it will give output only once.

You can omit the below extra lines. It just stores the tick data and prints later if needed. 

live_data = None
global live_data
live_data = message
print(live_data)

**Comment by echnidia-atig** [comment]
okay i'll try that
so if i want the data and make it work while some other code is working is that possible
i read somewhere that it gets stuck in the same cell.

**Comment by nprejit** [comment]
on_message function is threaded, so it runs in a separate thread while other code running. To use the data from on_message, use variables to store tick data and use it in different parts of your code. like earlier I used live_data

**Comment by echnidia-atig** [comment]
thanks a lot will try it :)

**Comment by echnidia-atig** [comment]
@nprejit 
i had another query
since i'll be using this for getting live feed so should i go with this or any other api for that??
i need data for every second??

**Comment by nprejit** [comment]
@echnidia-atig 
I also have an algo, for live tick data for index as well options, kotak's API for live feed is not that reliable for the live tick data, but yes, API for placing orders, cancelling, modifying, order report, trade report etc. are working fine. So I use kite API for live feed, then manipulate and place orders via kotak API.

**Comment by echnidia-atig** [comment]
i have tried using the kite api too before but it seemed a little complicated than the kotak api.
the login process also was a little longer and tedious 
so it would be great if you could lead the way regarding that and the live data.

**Comment by echnidia-atig** [comment]
and it is not free i believe they charge some fee for their services unlike other brokers?

**Comment by nprejit** [comment]
@echnidia-atig 
give me your email

**Comment by echnidia-atig** [comment]
@nprejit 
here it is : aadityanarainsingh@gmail.com

**Comment by nprejit** [comment]
> @nprejit here it is : [aadityanarainsingh@gmail.com](mailto:aadityanarainsingh@gmail.com)

check mail
