### ISSUE TITLE
Column dStrikePrice ends with ;

### ISSUE THREAD

**Issue by renjithsasidharan** [Kotak-Neo/kotak-neo-api#22]
Looking at script master for `nse_fo`, the column name `dStrikePrice` has `;` at the end.

<img width="228" alt="image" src="https://github.com/Kotak-Neo/kotak-neo-api/assets/4523060/8fc03fb1-87c1-4c5f-8030-41463cbc3ad2">

**Comment by Kotak-Neo** [comment]
We have noted your feedback down, will get this fixed.
