### ISSUE TITLE
Delivery position does not include the Avg Price

### ISSUE THREAD

**Issue by arun5068** [Kotak-Neo/kotak-neo-api#234]
Delivery position does not include the Avg Price

**Comment by dhanesh12twice** [comment]
Heyy can you get any response from client.quote method? Lot of kotak neo api users facing this issue.

**Comment by arun5068** [comment]
> Heyy can you get any response from client.quote method? Lot of kotak neo api users facing this issue.

I am not using python api

**Comment by dhanesh12twice** [comment]
But kotak only has Python sdk ryt?

**Comment by arun5068** [comment]
> But kotak only has Python sdk ryt?

i have written in C#
