### ISSUE TITLE
NIFTY 50 Index quote

### ISSUE THREAD

**Issue by syedasif11** [Kotak-Neo/kotak-neo-api#26]
`print('Subscribing to NIFTY Index token')`
`nifty_token = 26000`
`n_inst_token = [{"instrument_token": str(nifty_token), "exchange_segment": "Index"}]`
`client.subscribe(instrument_tokens=n_inst_token, isIndex=True)`

This is not working. Can you check what is wrong. Equity and FNO works fine.

**Comment by Kotak-Neo** [comment]
In place of token you have to pass Index Name, have updated this in the documentation, thanks for the feedback :)
