### ISSUE TITLE
quote api returns empty

### ISSUE THREAD

**Issue by renjithsasidharan** [Kotak-Neo/kotak-neo-api#29]
I am trying to get LTP for `BANKNIFTY2381745000PE`
`
inst_tokens = [{"instrument_token": '39040', "exchange_segment": 'nse_fo'}]
self.api.quotes(instrument_tokens=inst_tokens, quote_type='ltp', isIndex=True)
`

This returns `{}`. 
I have this problem only for FO not for CM

**Comment by syedasif11** [comment]
I believe `isIndex` should be `False`.

**Comment by shekar3110a** [comment]
This worked for me .. please try it out

client.quotes(instrument_tokens=[{"instrument_token": str(token) , "exchange_segment": 'nse_fo'}] ,
                      quote_type='', isIndex=False,
                      session_token=session_token, sid=sid,
                      server_id=serverid)

**Comment by Kotak-Neo** [comment]
Please put isIndex = False, and then it should work. :)
