### ISSUE TITLE
Unable to login using NeoAPI

### ISSUE THREAD

**Issue by prashantsp** [Kotak-Neo/kotak-neo-api#3]
Please help resolve this basic issue of logging in.

I have set the values for these variables access_token, consumer_key and consumer_secret from the napi.kotaksecutiriessite.

When this method is called client = NeoAPI(access_token=accessToken, consumer_key=consumerKey, consumer_secret=consumerSecret, environment='UAT',
                                on_message=on_message,
                                on_error=on_error)
try:
    # Login using password
    client.login(mobilenumber=mobileNumber, password=tradingPassword)
    print('Client', client)
except Exception as e:
    print("Exception when calling SessionApi->login: %s\n" % e)

Below ERROR is reported
**Exception when calling SessionApi->login: View Token hasn't been Generated Kindly Call the Login Function and Try to Generate OTP**

If the same method is called without access_key
Below ERROR is reported
**{"data": "{\"data\": {\"Code\": 401, \"Message\": \"Error occurred to initialise the session\"}}"}
Exception when calling SessionApi->login: can only concatenate str (not "NoneType") to str**

**Comment by prashantsp** [comment]
Where do i get the credentials for uat ?

**Comment by KSAPIHelp** [comment]
This facility is available on request basis. For further assistance, kindly reach out to Kotak Securities customer service team. They will be able to provide you with the necessary information and assist you with your request.
