### ISSUE TITLE
expiry date in script master

### ISSUE THREAD

**Issue by conquistadorjd** [Kotak-Neo/kotak-neo-api#30]
Hello, can you please confirm which column from scrip master is to be used as expiry date ?
e.g. if I look at script master file: https://lapi.kotaksecurities.com/wso2-scripmaster/v1/prod/2023-08-04/transformed/nse_fo.csv
There is column "lExpiryDate " however if seems to be in EPOCH format, however if I convert from epoch to date time, day and month is correct but year is 2013.
e.g. for pTrdSymbol = NIFTY2381017850CE, lExpiryDate  is 1376145000. This converted to normal date is Saturday, August 10, 2013 8:00:00 PM [GMT+05:30](https://www.epochconverter.com/timezones?q=1376145000)

If check if there is an issue with epoch date from your side or this date is in any different format ?

**Comment by Kotak-Neo** [comment]
Hi, the expiry time in the scrip master files is -10years, these files are directly fetched from the exchange, and no changes are made; that's why it is like this :)

**Comment by conquistadorjd** [comment]
also strike price is multiplied by 100, is it also fetched from exchange like this ?
