### ISSUE TITLE
Keep getting error "ERROR in HSWebscoket socket is already closed." while calling Quotes API

### ISSUE THREAD

**Issue by ratanlp** [Kotak-Neo/kotak-neo-api#33]
I keep getting errors on Quotes API call. I started getting this error from 3rd Aug, 2023 onwards.

_ERROR in HSWebscoket socket is already closed.
[OnError]: Function is running HSWebsocket
ERROR in HSWebscoket Connection is already closed.
[OnError]: Function is running HSWebsocket
ERROR in HSWebscoket 'NoneType' object has no attribute 'sock'
[OnError]: Function is running HSWebsocket
[OnClose]: Function is running HSWebsocket None_

What could be the reason?

**Comment by sacbhatia** [comment]
It can be because of connection or port issue. Check firewall settings. Alternatively, use on_connect and on_disconnect methods of websockets to log it and analyze.

**Comment by Kotak-Neo** [comment]
@ratanlp Please let us know if you are still facing the issue.
