### ISSUE TITLE
Websocket response - how to get rid of "updates ....." from printing on stdout?

### ISSUE THREAD

**Issue by AlbertBGeorge** [Kotak-Neo/kotak-neo-api#35]
<img width="1427" alt="image" src="https://github.com/Kotak-Neo/kotak-neo-api/assets/10909732/5ace17de-f9ff-490c-8e0d-bfbf0cffb5e3">

**Comment by syedasif11** [comment]
You can't do it from your own code. You will have to edit the Neo lib. Navigate to: `neo_api_client\HSWebSocketLib.py` line 968 and comment it out.

**Comment by AlbertBGeorge** [comment]
@syedasif11 Thanks for the workaround.
