### ISSUE TITLE
Login on every API call?

### ISSUE THREAD

**Issue by shusinghal** [Kotak-Neo/kotak-neo-api#43]
Hi.
Your docs suggest to use 'client' object before calling any method (place oder, modify, cancel, etc.)

Does this mean that I need to login again and again every single time? If yes, why did you opt this approach?

If I don't use your github code and rely only on API documentation, then I can create session one time and run x number of methods.

Like in your API documentation, can you allow making calls by passing token, sid, server? Or can you add API doc for quotes in postman?

**Comment by ShivdasBachewar** [comment]
it seems they have some session time, which is default to 3600 seconds (1 hr).
we can update that and we need not have to login again for specified period. 
https://napi.kotaksecurities.com/devportal/applications/

note: I was also facing same issue, I am also trying the same now.
after try please add your views

**Comment by shusinghal** [comment]
Hi Shidas,

client.modify_order(order_id = "", price = 0, quantity = 1, disclosed_quantity = 0, trigger_price = 0, validity = "GFD")

To use modify order, I need client object. This object is initiating the login process. If I have logged in one time, I should not require to login again till session timeout.

**Comment by syedasif11** [comment]
@shusinghal That may be because you are calling `client.login(mobilenumber=neo_creds.mobile_num, password=neo_creds.password)` again. This is what I am doing:
Ex.,
```

neo_object = None

def get_neo_client():
    if neo_object is not None:
        return neo_object
    # Normal login process
    client = NeoAPI(access_token=neo_creds.accesstoken.strip(), consumer_key=neo_creds.consumerkey.strip(),
                    consumer_secret=neo_creds.consumer_secret.strip(), environment='prod', on_close=None, on_open=None)
    .....
    .....
    # Once session is generated, set neo_object
    neo_object = client
```

**Comment by ShivdasBachewar** [comment]
> [shusinghal](/shusinghal)

As per my analysis,
once you are logged in to kotak api and generated session, 
generated session is used in all your subsequent request. 
Library is not doing re-login

**Comment by Kotak-Neo** [comment]
@shusinghal The library is not re-logging while calling any method. Please debug your code for rectifying this issue.
