### ISSUE TITLE
Unable to login , using the sample script from readme.md. Error - {"data": "{\"data\": {\"Code\": 401, \"Message\": \"Error occurred to initialise the session\"}}"}

### ISSUE THREAD

**Issue by vndn** [Kotak-Neo/kotak-neo-api#44]
Tried with both prod and uat as env 

`{"data": "{\"data\": {\"Code\": 401, \"Message\": \"Error occurred to initialise the session\"}}"}
Traceback (most recent call last):
  File "/home/vandan/tradeauto/kotak/trade.py", line 16, in <module>
    client.login(mobilenumber="+919087777398", password="Taktak24$")
  File "/home/vandan/tradeauto/env/lib/python3.10/site-packages/neo_api_client/neo_api.py", line 117, in login
    view_token = neo_api_client.LoginAPI(self.api_client).generate_view_token(password=password, mobilenumber=mobilenumber,
  File "/home/vandan/tradeauto/env/lib/python3.10/site-packages/neo_api_client/api/login_api.py", line 58, in generate_view_token
    header_params = {'Authorization': "Bearer " + self.api_client.configuration.bearer_token}
TypeError: can only concatenate str (not "NoneType") to str
`

`from neo_api_client import NeoAPI

def on_message(message):
    print(message)
    
def on_error(error_message):
    print(error_message)
    
client = NeoAPI(consumer_key=consumer_key_here, consumer_secret=consumer_secret_here, 
                environment='prod', on_message=on_message, on_error=on_error, on_close=None, on_open=None)

client.login(mobilenumber="+91########3", password="*******")`

**Comment by Kotak-Neo** [comment]
As @shusinghal mentioned you seem to be making a mistake in passing params, please debug your code to rectify.
