### ISSUE TITLE
Need clarity on few points

### ISSUE THREAD

**Issue by shusinghal** [Kotak-Neo/kotak-neo-api#50]
After all day trade, I want to run API to close/square off all open positions at 3:15 pm. This is just in case if there is an error and positions doesn't get close. In this scenario:
1. Do I need to use client.positions() or there is alternate way. I don't want to use 'client' as it authenticates again. Instead I would like to use access_token, token, hsServerId, and server key to call positions API.
2. In positions API, which parameter or key tells me that a position is open?
3. When I call place order API, I need to check status of API. Can you tell me all possible values of 'ordSt' in order status API success response? My code broke because ordSt returned some values that are not documented and hence I didn't consider in code.

Thanks

**Comment by Kotak-Neo** [comment]
Hi, @shusinghal Have updated the positions doc, kindly have a look it'll resolve most of your queries. Also for reusing the session, you can have a look at the pull requests created.
Will be including the ordSt table in the documentation.
