### ISSUE TITLE
Error during order placement: {'stat': 'Not_Ok', 'stCode': 5202, 'errMsg': 'Error: Invalid Request'}

### ISSUE THREAD

**Issue by mshh9** [Kotak-Neo/kotak-neo-api#55]
I am getting this error while placing an order. I am able to login and get the scrip name but having issue while placing order. 
**Here is the line of code**
client.place_order(exchange_segment="nse_fo", product="NRML", price="", order_type="MKT", quantity="15",\
                           validity="DAY",\
                           trading_symbol="BANKNIFTY2391345000PE",\
                           transaction_type="B", amo="NO", disclosed_quantity="", market_protection="0", pf="N",\
                           trigger_price="", tag="Try")
**This is the response**
Out[34]: {'stat': 'Not_Ok', 'stCode': 5202, 'errMsg': 'Error: Invalid Request'}

**Comment by mshh9** [comment]
disclosed_quantity="" - this has to be disclosed_quantity="0" and it works. closing the issue

**Comment by dsp1589** [comment]
were you able to create order successfully?

**Comment by ravisubbu97** [comment]
No matter how much i try, i am getting the same issue.. 
{'stat': 'Not_Ok', 'stCode': 5202, 'errMsg': 'Error: Invalid Request', 'tid': 'server7_894264'}

my place order code is

trade_status = client.place_order(exchange_segment="nse_cm", product="NRML", price="", order_type="MKT", quantity=Quantity, validity="DAY", disclosed_quantity="0", trading_symbol=stock,
                                      transaction_type=type, amo="NO", market_protection="0", pf="N",
                                      trigger_price="", tag=None)
                                      
Can you help..?
