### ISSUE TITLE
Avg price and current price in positions api

### ISSUE THREAD

**Issue by mshh9** [Kotak-Neo/kotak-neo-api#57]
Do you have any plans to bring average price of the order and the current price of the scrip in positions like it was previously. I used to calculate the unrealised PnL using the two price values. Is there any way to calculate PnL now? Also what is cfBuyAmt and cfSellAmt

**Comment by Kotak-Neo** [comment]
@mshh9 Have updated the [Positions Documentation](https://github.com/Kotak-Neo/kotak-neo-api/blob/main/docs/Positions.md) and included the calculation logics.
