### ISSUE TITLE
ModuleNotFoundError: No module named 'neo_api_client'

### ISSUE THREAD

**Issue by Abhinawkhandelwal** [Kotak-Neo/kotak-neo-api#58]
I have installed the pip - pip install "git+https://github.com/Kotak-Neo/kotak-neo-api.git#egg=neo_api_client"
but getting this error
![image](https://github.com/Kotak-Neo/kotak-neo-api/assets/144726305/78987f6a-4f2c-4887-85d0-077c9661b3ac)

**Comment by shusinghal** [comment]
in your terminal, run the command 'git freeze'. It provides list of all modules available to that project. Check if neo-api-client is available there. If not, install again. If it is there, try importing any other package and see if code runs.

**Comment by Hari3115** [comment]
Restart the terminal post pip installation and then try the login process

**Comment by Kotak-Neo** [comment]
@Abhinawkhandelwal Hope this has been resolved, closing the issue. :)
