### ISSUE TITLE
Position Data does not Contain Order Number.

### ISSUE THREAD

**Issue by rosevinod** [Kotak-Neo/kotak-neo-api#77]
Dear,

I want to modify the order based on my position.
The position data does not contain the order number.
I need the order number of open positions to perform any action.

Please suggest.
Thanks,

**Comment by geek-coder** [comment]
Positions data won't contain order numbers. 
You can use following apis to fetch open orders.
None of brokers give order number or even ltp of postions in their postions api. (Can say for 5paisa, zerodha, shoonya, prostocks, fyers ).
You need to see positions, get your trading symbols, and then fetch LTP or open orders for those trading symbols and take whatever action you wish to take.

# Get Order Book
client.order_report()

# Get Order History
client.order_history(order_id = "")

**Comment by rosevinod** [comment]
@geek-coder Thanks bro.
