### ISSUE TITLE
Documentation or root cause analysis for Not_Ok response in position api

### ISSUE THREAD

**Issue by shusinghal** [Kotak-Neo/kotak-neo-api#82]
Hi.

I cannot find any documentation or RCA method for the given error. Please help.
{'stat': 'Not_Ok', 'errMsg': 'No Data', 'stCode': 5203, 'tid': 'server2_6286991'}

What is 5203?

**Comment by rosevinod** [comment]
Position API gave "No Data" means you don't have any position during the live market for today only.
