### ISSUE TITLE
Quote api not working since 6 Nov

### ISSUE THREAD

**Issue by arunjain9988** [Kotak-Neo/kotak-neo-api#89]
Tried this code 

inst_tokens = [ {"instrument_token": "13245", "exchange_segment": "nse_cm"} ]
a = client.quotes(instrument_tokens=inst_tokens, quote_type="ltp", isIndex=False)
print(a)

Getting This Error:
ERROR in HSWebscoket [Errno 61] Connection refused
[OnError]: Function is running HSWebsocket
[OnClose]: Function is running HSWebsocket None
{'message': ConnectionRefusedError(61, 'Connection refused')}

This was working till Friday, but not working now, please resolve

**Comment by imdigitalcon** [comment]
I can confirm , its not working. Same error.

**Comment by imdigitalcon** [comment]
Its working now, may be some issue from kotaks side
