### ISSUE TITLE
OTP is not generating

### ISSUE THREAD

**Issue by sacbhatia** [Kotak-Neo/kotak-neo-api#9]
Received below response upon OTP request

{"data": {"access_token": "eyJ4NXQiOiJTm1NNU1qTXpNR1kyWm1OaFpHUTFNakE1TmciLCJraWQiOiJaalJqTUdRek9URmhPV1EwTm1WallXWTNZemRtWkdOa1pUUmpaVEUxTlRnMFkyWTBZVEUyTlRCaVlURTRNak5tWkRVeE5qZ3pPVGM0TWpGbFkyWXpOUV9SUzI1NiIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJjbGllbnQxNTY1IiwiYXV0IjoiQVBQTElDQVRJT04iLCJhdWQiOiJpcnEzT2NvYzJLXzBmbWZoNGNfS00xZUFTS01hIiwibmJmIjoxNjg5NzUzOTEyLCJhenAiOiJpcnEzT2NvYzJLXzBmbWZoNGNfS00xZUFTS01hIiwic2NvcGUiOiJkZWZhdWx0IiwiaXNzIjoiaHR0cHM6XC9cL25hcGkua290YWtzZWN1cml0aWVzLmNvbTo0NDNcL29hdXRoMlwvdG9rZW4iLCJleHAiOjE2ODk3NTc1MTIsImlhdCI6MTY4OTc1MzkxMiwianRpIjoiNmExNTMyNjItNGM1MC00ZThkLWJhZDktNmE5N2NmMWM4NmM3In0.FUwZanYdwzgBYw54SGyvmVIpl8BlpcDwrl_TvDF0T6CAqQlQniMbnHTNkzPlr7PdZHaS7fKkQIeDIrWgVI48J4_U4Hf2Y4QGDwl7tfjygbNRqgRrD71CR9WIOaTlfi6LBydYRJWlJWMIVMBCl69lo9foAzyTmNgd0y6AdVdhvGmKihJly1yJyJm1KwOFmVOJ1kEa-5bBw9UEdqNh8SvytWjBr8ikV2743ZB82x90ZNmAePHhXFtcYEydRGK5uZPl4Hsj4tsRLN9PyoaL5UGjI01jr2fhdYRfk5BwPPjrp0bduxMLXU9YlS9abc7JhF2OS5OFoYZktRlnqJIqePqabA", "scope": "default", "token_type": "Bearer", "expires_in": 3600}}
{'error': [{'code': '10522', 'message': 'Issues while generating OTP! Try to login again.'}]}

**Comment by Kotak-Neo** [comment]
That's unusual, please share your Mobile Number we'll connect to understand the issue.

**Comment by PraveenChordia** [comment]
> Received below response upon OTP request
> 
> {"data": {"access_token": "eyJ4NXQiOiJTm1NNU1qTXpNR1kyWm1OaFpHUTFNakE1TmciLCJraWQiOiJaalJqTUdRek9URmhPV1EwTm1WallXWTNZemRtWkdOa1pUUmpaVEUxTlRnMFkyWTBZVEUyTlRCaVlURTRNak5tWkRVeE5qZ3pPVGM0TWpGbFkyWXpOUV9SUzI1NiIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJjbGllbnQxNTY1IiwiYXV0IjoiQVBQTElDQVRJT04iLCJhdWQiOiJpcnEzT2NvYzJLXzBmbWZoNGNfS00xZUFTS01hIiwibmJmIjoxNjg5NzUzOTEyLCJhenAiOiJpcnEzT2NvYzJLXzBmbWZoNGNfS00xZUFTS01hIiwic2NvcGUiOiJkZWZhdWx0IiwiaXNzIjoiaHR0cHM6XC9cL25hcGkua290YWtzZWN1cml0aWVzLmNvbTo0NDNcL29hdXRoMlwvdG9rZW4iLCJleHAiOjE2ODk3NTc1MTIsImlhdCI6MTY4OTc1MzkxMiwianRpIjoiNmExNTMyNjItNGM1MC00ZThkLWJhZDktNmE5N2NmMWM4NmM3In0.FUwZanYdwzgBYw54SGyvmVIpl8BlpcDwrl_TvDF0T6CAqQlQniMbnHTNkzPlr7PdZHaS7fKkQIeDIrWgVI48J4_U4Hf2Y4QGDwl7tfjygbNRqgRrD71CR9WIOaTlfi6LBydYRJWlJWMIVMBCl69lo9foAzyTmNgd0y6AdVdhvGmKihJly1yJyJm1KwOFmVOJ1kEa-5bBw9UEdqNh8SvytWjBr8ikV2743ZB82x90ZNmAePHhXFtcYEydRGK5uZPl4Hsj4tsRLN9PyoaL5UGjI01jr2fhdYRfk5BwPPjrp0bduxMLXU9YlS9abc7JhF2OS5OFoYZktRlnqJIqePqabA", "scope": "default", "token_type": "Bearer", "expires_in": 3600}} {'error': [{'code': '10522', 'message': 'Issues while generating OTP! Try to login again.'}]}

Maybe your token has expired, could you try regenerating the access token?

**Comment by sacbhatia** [comment]
Hey
I was using pwd one that is used for NEST. Realized Neo accounts have 2 password, one for NEST, other for Neo Web. API requires pwd for Neo Web. It worked.

**Comment by vishalsaini0905** [comment]
i am also not able to generate otp.
error :- Exception when calling SessionApi->session_2fa: View Token hasn't been Generated Kindly Call the Login Function and Try to Generate OTP

**Comment by PraveenChordia** [comment]
> i am also not able to generate otp. error :- Exception when calling SessionApi->session_2fa: View Token hasn't been Generated Kindly Call the Login Function and Try to Generate OTP
Hi, have you generated, what consumer key and consumer secret are you using when creating the client?
also the client.login should have your neo credentials.
NOTE: Kotak has two trading api's one is NEO and other is old NEST api, so you have to register on NEO and get your consumer keys from there and use Kotak NEO credentials for it.
I hope it helps
