### ISSUE TITLE
What is the difference between client.quotes and client.subscribe?

### ISSUE THREAD

**Issue by Thushar-marvel** [Kotak-Neo/kotak-neo-api#90]
I wanted to know the exact difference between client.quotes() and client.subscribe()?
if i run client.quotes() in a continous loop, will this be same as client.subscribe()?
also let me know the complexity of these 2 functions, which one has low latency?
Thank you

**Comment by Prrix** [comment]
no client.quotes() works on get method and thus carries a latency while subscribe works on websocket that is way faster though implementation is a little quirky 
also client.quotes() happens to fault on data sometimes

**Comment by Thushar-marvel** [comment]
> no client.quotes() works on get method and thus carries a latency while subscribe works on websocket that is way faster though implementation is a little quirky also client.quotes() happens to fault on data sometimes

Thank you @Prrix
