### ISSUE TITLE
Need an api for net mtm pnl

### ISSUE THREAD

**Issue by AnupamSharma6** [Kotak-Neo/kotak-neo-api#93]
Hi Team,
Can you please provide an api for streaming the net mtm pnl please?

**Comment by Kotak-Neo** [comment]
You may use positions API to calculate PnL. Please refer to the [Positions Doc](https://github.com/Kotak-Neo/kotak-neo-api/blob/main/docs/Positions.md).

**Comment by 1513janakbarman** [comment]
19731
